spring:
  application:
    name: appi-zuul
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
      # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5

server:
  port: 5555
zuul:
  routes:
    rbac:
      path: /a/rbac/**
      serviceId: rbac-service
    business:
      path: /a/business/**
      serviceId: business-service
    client:
      path: /u/client/**
      serviceId: eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/



